### PR TITLE
compatibility and testing with recent debug releases

### LINKED ISSUE #20: broken with debug@4
```
  when preloaded with -r, automatically logs all debug calls with log level debug to a default pino logger
not ok Cannot find module 'debug/src/debug.js'
    stack: |
      Test.tap.afterEach (test/index.js:25:15)
    at:
      line: 548
      column: 15
      file: module.js
      function: Function.Module._resolveFilename
    code: MODULE_NOT_FOUND
    test: >-
      when preloaded with -r, automatically logs all debug calls with log level
      debug to a default pino logger
```

from pino-integration

### PR DESCRIPTION
**Pull request by jstewmon**
Fixes #20 #21

### CODE REVIEW

**Comment by mcollina** [comment]
This is fabolous work!

**Comment by jstewmon** [comment]
Thanks! I made one last edit to check lastIndexOf >= 0 instead of > 0 (I don't think it would ever matter, but I wanted the check to be correct).

I'm happy to help maintain when I can.

**Comment by jstewmon** [comment]
@mcollina thanks for the prompt and kind review.

Do we need to solicit feedback from anyone else? I'm eager to see this merged and released. :-)

**Comment by mcollina** [comment]
Nope, I just needed to do a release!

**Pull request merged**
