### PR TITLE
Changed "autoenable" to "auto" in programmatic server example script.

### PR DESCRIPTION
**Pull request by colmose**
Example server will default to auto: true as "auto" is not passed in from example script.

Just having a play with pino-debug and think I spotted a spelling error in the example script. 

The options passed into the pino instance has `autoenable` but I reckon it should be `auto`.
It doesn't make any difference to the default settings as it's set to true by default but might help with readability in future.

### CODE REVIEW

**Comment by mcollina** [comment]
Can you please remove .idea/libraries/pino_debug_node_modules.xml and add `.idea` into `.gitignore`?

**Comment by colmose** [comment]
Apologies, done!

**Comment by davidmarkclements** [comment]
Yes @colmose you're right, I renamed it and missed a spot, thank you!

**Comment by colmose** [comment]
:+1:

**Pull request merged**
