### PR TITLE
add support for extend and test with debug@4.1

### LINKED ISSUE #24: debug.extend is not a function
I get TypeError: debug.extend is not a function when using debug.extend any pointers on how to fix this would be great.

```const pinoDebug = require('pino-debug')
const logger = require('pino')({level: process.env.LEVEL || 'info'}, process.stderr);
pinoDebug(logger, {
  map: {
    'module:*': 'info',
    '*': 'trace' // everything else - trace
  }
});

const debug = require('debug')('module:hello');
const trace = debug.extend('world');

trace('Some traceable log statement')
```

### PR DESCRIPTION
**Pull request by jstewmon**
fixes #24

### CODE REVIEW

**Comment by davidmarkclements** [comment]
Sorry if this a silly question, my head isn’t in this right now, but can we pass through to debugs extend implantation rather than re-implementing? This would mean wed automatically track any changes/bug fixes

**Comment by jstewmon** [comment]
I don’t see an obvious way based on our current wrapper. Maybe if we could load and patch the node/browser modules to cause debug args to pass to the pino logger. I don’t have time to work on it right now, so I just focused on patching the reported issue.

**Comment by jstewmon** [comment]
@davidmarkclements are you good w this for now, or did you want to investigate an alternate approach?

**Comment by davidmarkclements** [comment]
yeah cool it's fine thanks @jstewmon

**Pull request merged**
